# Generated by Django 4.1.1 on 2022-09-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcliente', models.CharField(max_length=500)),
                ('nombrecompania', models.CharField(max_length=500)),
                ('direccionfacturacion', models.CharField(max_length=500)),
                ('ciudad', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
