# Generated by Django 4.1.1 on 2022-09-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cliente_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='idcliente',
        ),
    ]
